export const hobbies = [
    "Reading",
    "Writing",
    "Painting",
    "Drawing",
    "Cooking",
    "Baking",
    "Gardening",
    "Hiking",
    "Camping",
    "Fishing",
    "Knitting",
    "Sewing",
    "Playing musical instruments",
    "Singing",
    "Dancing",
    "Photography",
    "Bird watching",
    "Traveling",
    "Playing board games",
    "Playing video games",
    "Solving puzzles",
    "Crafting",
    "Woodworking",
    "Playing sports",
    "Running",
    "Cycling",
    "Yoga",
    "Meditation",
    "Collecting stamps",
    "Collecting coins"
  ];
  