export const hobbiesarr = [
  "Yoga",
  "Baking",
  "Hiking",
  "Reading",
  "Writing",
  "Drawing",
  "Cooking",
  "Camping",
  "Fishing",
  "Sewing",
  "Singing",
  "Dancing",
  "Running",
  "Cycling",
  "Painting",
  "Knitting",
  "Crafting",
  "Traveling",
  "Gardening",
  "Meditation",
  "Photography",
  "Woodworking",
  "Bird watching",
  "Playing sports",
  "Solving puzzles",
  "Collecting stamps",
  "Collecting coins",
  "Playing board games",
  "Playing video games",
  "Playing musical instruments",
];
